package ch.checkmarx.jsf.sample;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.io.Serializable;
import java.util.Arrays;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Map;

@ManagedBean(name="userBean")
@SessionScoped
public class UserBean  implements Serializable {
    private static Map<String, Object> fruit2Value;
    private static Map<String, Object> color2Value;
    private static Map<String, Object> year2Value;
    private static Map<String, Object> food2Value;
    private static Map<String, Object> coffee2Value;

    static {
        coffee2Value = new LinkedHashMap<String, Object>();
        coffee2Value.put("Cream Latte", "Cream Latte"); //label, value
        coffee2Value.put("Extreme Mocha", "Extreme Mocha");
        coffee2Value.put("Buena Vista", "Buena Vista");
        food2Value = new LinkedHashMap<String, Object>();
        food2Value.put("Fry Checken", "Fry Checken"); //label, value
        food2Value.put("Tomyam Soup", "Tomyam Soup");
        food2Value.put("Mixed Rice", "Mixed Rice");
        year2Value = new LinkedHashMap<String, Object>();
        year2Value.put("2000", "2000"); //label, value
        year2Value.put("2010", "2010");
        year2Value.put("2020", "2020");
        color2Value = new LinkedHashMap<String, Object>();
        color2Value.put("Red", "Red"); //label, value
        color2Value.put("Green", "Green");
        color2Value.put("Blue", "Blue");
        fruit2Value = new LinkedHashMap<String, Object>();
        fruit2Value.put("Banana", "Banana"); //label, value
        fruit2Value.put("Banana", "Banana");
        fruit2Value.put("PineApple", "PineApple");
        fruit2Value.put("Peach", "Peach");
        fruit2Value.put("Pear", "Pear");
    }

    public boolean rememberMe;
    public Fruit[] fruit1Value;
    public Color[] color3List;
    public Year[] year3List;
    public Food[] food3List;
    public Coffee[] coffee3List;
    private String username;
    private String password;
    private String address;
    private String sex;
    private Date dateOfBirth;
    private int age;
    private double percentage;
    private String favFruit1[];
    private String favFruit2[];
    private String favFruit3[];
    private String favFruit4[];
    private String favColor1;
    private String favColor2;
    //Generated by Map
    private String favColor3;
    private String favYear1;
    private String favYear2;
    private String favYear3;
    private String[] favFood1;
    private String[] favFood2;
    private String[] favFood3;
    private String favCoffee1;
    private String favCoffee2;
    private String favCoffee3;
    private boolean checkBoxValue;

    public static Map<String, Object> getColor2Value() {
        return color2Value;
    }

    public static void setColor2Value(Map<String, Object> color2Value) {
        UserBean.color2Value = color2Value;
    }

    public Map<String, Object> getFavCoffee2Value() {
        return coffee2Value;
    }

    public Map<String, Object> getFavFood2Value() {
        return food2Value;
    }

    public Map<String, Object> getFavYear2Value() {
        return year2Value;
    }

    public Map<String, Object> getFavFruitValue() {
        return fruit2Value;
    }

    //Generated by Array
    public String[] getFavFruit2Value() {

        favFruit2 = new String[5];
        favFruit2[0] = "Banana";
        favFruit2[1] = "Apple";
        favFruit2[2] = "Pineapple";
        favFruit2[3] = "Peach";
        favFruit2[4] = "Pear";

        return favFruit2;
    }

    public Fruit[] getFavFruit1Value() {

        fruit1Value = new Fruit[5];
        fruit1Value[0] = new Fruit("Banana", "Banana"); //label, value
        fruit1Value[1] = new Fruit("Apple", "Apple");
        fruit1Value[2] = new Fruit("PineApple", "PineApple");
        fruit1Value[3] = new Fruit("Peach", "Peach");
        fruit1Value[4] = new Fruit("Pear", "Pear");

        return fruit1Value;
    }

    public String getFavFruit4InString() {
        return Arrays.toString(favFruit4);
    }

    public Map<String, Object> getFavColor2Value() {
        return color2Value;
    }

    public Color[] getFavColor3Value() {

        color3List = new Color[3];
        color3List[0] = new Color("Red", "Red");
        color3List[1] = new Color("Green", "Green");
        color3List[2] = new Color("Blue", "Blue");

        return color3List;
    }

    public Year[] getFavYear3Value() {

        year3List = new Year[3];
        year3List[0] = new Year("2000", "2000");
        year3List[1] = new Year("2010", "2010");
        year3List[2] = new Year("2020", "2020");

        return year3List;
    }

    public Food[] getFavFood3Value() {

        food3List = new Food[3];
        food3List[0] = new Food("Fry Checken", "Fry Checken");
        food3List[1] = new Food("Tomyam Soup", "Tomyam Soup");
        food3List[2] = new Food("Mixed Rice", "Mixed Rice");

        return food3List;
    }

    public Coffee[] getFavCoffee3Value() {

        coffee3List = new Coffee[3];
        coffee3List[0] = new Coffee("Cream Latte", "Cream Latte");
        coffee3List[1] = new Coffee("Extreme Mocha", "Extreme Mocha");
        coffee3List[2] = new Coffee("Buena Vista", "Buena Vista");

        return coffee3List;

    }

    public double getPercentage() {
        return percentage;
    }

    public void setPercentage(double percentage) {
        this.percentage = percentage;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public String getFavCoffee1() {
        return favCoffee1;
    }

    public void setFavCoffee1(String favCoffee1) {
        this.favCoffee1 = favCoffee1;
    }

    public String getFavCoffee2() {
        return favCoffee2;
    }

    public void setFavCoffee2(String favCoffee2) {
        this.favCoffee2 = favCoffee2;
    }

    public String getFavCoffee3() {
        return favCoffee3;
    }

    public void setFavCoffee3(String favCoffee3) {
        this.favCoffee3 = favCoffee3;
    }

    public String getFavFruit2InString() {
        return Arrays.toString(favFruit2);
    }

    public String getFavFood2InString() {
        return Arrays.toString(favFood2);
    }

    public String getFavFood1InString() {
        return Arrays.toString(favFood1);
    }

    public String getFavFood3InString() {
        return Arrays.toString(favFood3);
    }

    public String getFavFruit3InString() {
        return Arrays.toString(favFruit3);
    }

    public boolean getRememberMe() {
        return rememberMe;
    }

    public boolean isRememberMe() {
        return rememberMe;
    }

    public void setRememberMe(boolean rememberMe) {
        this.rememberMe = rememberMe;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String[] getFavFruit1() {
        return favFruit1;
    }

    public void setFavFruit1(String[] favFruit1) {
        this.favFruit1 = favFruit1;
    }

    public String[] getFavFruit2() {
        return favFruit2;
    }

    public void setFavFruit2(String[] favFruit2) {
        this.favFruit2 = favFruit2;
    }

    public String[] getFavFruit3() {
        return favFruit3;
    }

    public void setFavFruit3(String[] favFruit3) {
        this.favFruit3 = favFruit3;
    }

    public String[] getFavFruit4() {
        return favFruit4;
    }

    public void setFavFruit4(String[] favFruit4) {
        this.favFruit4 = favFruit4;
    }

    public void setFruit1Value(Fruit[] fruit1Value) {
        this.fruit1Value = fruit1Value;
    }

    public String getFavColor1() {
        return favColor1;
    }

    public void setFavColor1(String favColor1) {
        this.favColor1 = favColor1;
    }

    public String getFavColor3() {
        return favColor3;
    }

    public void setFavColor3(String favColor3) {
        this.favColor3 = favColor3;
    }

    public boolean isCheckBoxValue() {
        return checkBoxValue;
    }

    public void setCheckBoxValue(boolean checkBoxValue) {
        this.checkBoxValue = checkBoxValue;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String sayHello() {
        return "response";
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }


    public String getFavFruit1InString() {
        return Arrays.toString(favFruit1);
    }

    public String getFavColor2() {
        return favColor2;
    }

    public void setFavColor2(String favColor2) {
        this.favColor2 = favColor2;
    }

    public String[] getFavFood1() {
        return favFood1;
    }

    public void setFavFood1(String[] favFood1) {
        this.favFood1 = favFood1;
    }

    public String[] getFavFood2() {
        return favFood2;
    }

    public void setFavFood2(String[] favFood2) {
        this.favFood2 = favFood2;
    }

    public String[] getFavFood3() {
        return favFood3;
    }

    public void setFavFood3(String[] favFood3) {
        this.favFood3 = favFood3;
    }

    public String getFavYear1() {
        return favYear1;
    }

    public void setFavYear1(String favYear1) {
        this.favYear1 = favYear1;
    }

    public String getFavYear2() {
        return favYear2;
    }

    public void setFavYear2(String favYear2) {
        this.favYear2 = favYear2;
    }

    public String getFavYear3() {
        return favYear3;
    }

    public void setFavYear3(String favYear3) {
        this.favYear3 = favYear3;
    }

    public static class Fruit {
        public String fruitLabel;
        public String fruitValue;


        public Fruit(String fruitLabel, String fruitValue) {
            this.fruitLabel = fruitLabel;
            this.fruitValue = fruitValue;
        }

        public String getFruitLabel() {
            return fruitLabel;
        }

        public void setFruitLabel(String fruitLabel) {
            this.fruitLabel = fruitLabel;
        }

        public String getFruitValue() {
            return fruitValue;
        }

        public void setFruitValue(String fruitValue) {
            this.fruitValue = fruitValue;
        }
    }

    //Generated by Object array
    public static class Color {
        public String colorLabel;
        public String colorValue;

        public Color(String colorLabel, String colorValue) {
            this.colorLabel = colorLabel;
            this.colorValue = colorValue;
        }

        public String getColorLabel() {
            return colorLabel;
        }

        public String getColorValue() {
            return colorValue;
        }

    }

    public static class Year {
        public String yearLabel;
        public String yearValue;

        public Year(String yearLabel, String yearValue) {
            this.yearLabel = yearLabel;
            this.yearValue = yearValue;
        }

        public String getYearLabel() {
            return yearLabel;
        }

        public String getYearValue() {
            return yearValue;
        }

    }

    public static class Food {
        public String foodLabel;
        public String foodValue;

        public Food(String foodLabel, String foodValue) {
            this.foodLabel = foodLabel;
            this.foodValue = foodValue;
        }

        public String getFoodLabel() {
            return foodLabel;
        }

        public String getFoodValue() {
            return foodValue;
        }

    }

    public static class Coffee {
        public String coffeeLabel;
        public String coffeeValue;

        public Coffee(String coffeeLabel, String coffeeValue) {
            this.coffeeLabel = coffeeLabel;
            this.coffeeValue = coffeeValue;
        }

        public String getCoffeeLabel() {
            return coffeeLabel;
        }

        public String getCoffeeValue() {
            return coffeeValue;
        }

    }
}